--вывести название, выводит типа ауид 301 комп
use UNIVER
select AUDITORIUM.AUDITORIUM_NAME, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
from AUDITORIUM inner join AUDITORIUM_TYPE
on AUDITORIUM.AUDITORIUM_TYPE= AUDITORIUM_TYPE.AUDITORIUM_TYPE
where AUDITORIUM_NAME = '301-1'

select AUDITORIUM.AUDITORIUM_NAME, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
from AUDITORIUM, AUDITORIUM_TYPE
where AUDITORIUM.AUDITORIUM_TYPE= AUDITORIUM_TYPE.AUDITORIUM_TYPE
and AUDITORIUM_NAME = (select AUDITORIUM_NAME from AUDITORIUM where AUDITORIUM_NAME = '301-1' )
--кол-во аудит каждого вида
select AUDITORIUM_TYPE.AUDITORIUM_TYPE, Count(*)[кол-во]
from AUDITORIUM_TYPE
group by AUDITORIUM_TYPE