use UNIVER
Select * from PROGRESS FULL OUTER JOIN  STUDENT
On PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where STUDENT.IDSTUDENT is Null
order by STUDENT.IDSTUDENT

select * from STUDENT full outer join PROGRESS
on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
where PROGRESS.IDSTUDENT is null
order by PROGRESS.IDSTUDENT

select * from STUDENT full outer join PROGRESS 
on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
where PROGRESS.IDSTUDENT is not null
